### PR TITLE
 Adds invalidate method to MemCacheMapping 

### PR DESCRIPTION
**Pull request by rber474**
Adds invalidate method to MemCacheMapping class, trying to fix https://github.com/dataflake/Products.mcdutils/issues/8

### CODE REVIEW

**Comment by rber474** [comment]
Tests passed

**Review by erral — APPROVED** [review]

**Review by dataflake — CHANGES_REQUESTED** [review]
This PR is missing unit tests and a change log entry.

**Comment by rber474** [comment]
added unittest and log entry

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
Thank you for your help on this, version 4.1 is now published.

**Pull request merged**
